<a href="https://colab.research.google.com/github/THAMARAISELVI0805/CODSOFT/blob/main/Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import tensorflow.keras as tf

In [24]:
ratings = pd.read_csv("/content/ratings.csv.zip")
books = pd.read_csv("/content/books.csv.zip")

In [6]:
ratings.head(5)

book_id  user_id  rating
0        1      314       5
1        1      439       3
2        1      588       5
3        1     1169       4
4        1     1185       4

In [28]:
books.head(5)

id  book_id  best_book_id  work_id  books_count       isbn        isbn13  \
0   1  2767052       2767052  2792775          272  439023483  9.780439e+12   
1   2        3             3  4640799          491  439554934  9.780440e+12   
2   3    41865         41865  3212258          226  316015849  9.780316e+12   
3   4     2657          2657  3275794          487   61120081  9.780061e+12   
4   5     4671          4671   245494         1356  743273567  9.780743e+12   

                       authors  original_publication_year  \
0              Suzanne Collins                     2008.0   
1  J.K. Rowling, Mary GrandPré                     1997.0   
2              Stephenie Meyer                     2005.0   
3                   Harper Lee                     1960.0   
4          F. Scott Fitzgerald                     1925.0   

                             original_title  ... ratings_count  \
0                          The Hunger Games  ...       4780653   
1  Harry Potter and the Philosopher's Stone  ...       4602479   
2                                  Twilight  ...       3866839   
3                     To Kill a Mockingbird  ...       3198671   
4                          The Great Gatsby  ...       2683664   

  work_ratings_count  work_text_reviews_count  ratings_1  ratings_2  \
0            4942365                   155254      66715     127936   
1            4800065                    75867      75504     101676   
2            3916824                    95009     456191     436802   
3            3340896                    72586      60427     117415   
4            2773745                    51992      86236     197621   

   ratings_3  ratings_4  ratings_5  \
0     560092    1481305    2706317   
1     455024    1156318    3011543   
2     793319     875073    1355439   
3     446835    1001952    1714267   
4     606158     936012     947718   

                                           image_url  \
0  https://images.gr-assets.com/books/1447303603m...   
1  https://images.gr-assets.com/books/1474154022m...   
2  https://images.gr-assets.com/books/1361039443m...   
3  https://images.gr-assets.com/books/1361975680m...   
4  https://images.gr-assets.com/books/1490528560m...   

                                     small_image_url  
0  https://images.gr-assets.com/books/1447303603s...  
1  https://images.gr-assets.com/books/1474154022s...  
2  https://images.gr-assets.com/books/1361039443s...  
3  https://images.gr-assets.com/books/1361975680s...  
4  https://images.gr-assets.com/books/1490528560s...  

[5 rows x 23 columns]

In [10]:
nbooks = ratings.book_id.nunique()
nusers = ratings.user_id.nunique()

In [11]:
print(nbooks)
print(nusers)

10000
53424


In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test = train_test_split(ratings,test_size=0.2,random_state=10)

In [13]:
book_input = tf.Input(shape=[1])# [64,1]
book_embedding = tf.layers.Embedding(nbooks+1,15)(book_input)
book_out = tf.layers.Flatten()(book_embedding)

user_input = tf.Input(shape=[1])# [64,1]
user_embedding =tf.layers.Embedding(nusers+1,15)(user_input)
user_out = tf.layers.Flatten()(user_embedding)

concadinate = tf.layers.Concatenate()([book_out,user_out])
dense_1 = tf.layers.Dense(128,activation='relu')(concadinate)
out = tf.layers.Dense(1,activation="relu")(dense_1)

model = tf.Model([book_input,user_input],out)

In [20]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 1)]                  0         []                            
                                                                                                  
 input_2 (InputLayer)        [(None, 1)]                  0         []                            
                                                                                                  
 embedding (Embedding)       (None, 1, 15)                150015    ['input_1[0][0]']             
                                                                                                  
 embedding_1 (Embedding)     (None, 1, 15)                801375    ['input_2[0][0]']             
                                                                                              

In [16]:
model.compile(optimizer='adam',loss="mean_squared_error")

In [29]:
model.fit([x_train.book_id,x_train.user_id],x_train.rating,validation_data=([x_test.book_id,x_test.user_id],x_test.rating),epochs=5,batch_size=64)

Epoch 1/5
12272/12272 [==============================] - 197s 16ms/step - loss: 0.5550 - val_loss: 0.7278
Epoch 2/5
12272/12272 [==============================] - 221s 18ms/step - loss: 0.5218 - val_loss: 0.7394
Epoch 3/5
12272/12272 [==============================] - 217s 18ms/step - loss: 0.4858 - val_loss: 0.7531
Epoch 4/5
12272/12272 [==============================] - 222s 18ms/step - loss: 0.4503 - val_loss: 0.7829
Epoch 5/5
12272/12272 [==============================] - 213s 17ms/step - loss: 0.4179 - val_loss: 0.8042


In [30]:
model.save("recommander")

In [31]:
b_id=list(ratings.book_id.unique())

In [32]:
b_id

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [36]:
book_arr=np.array(b_id) #get all book 10s
user=np.array([80 for i in range(len(b_id))])

In [37]:
pred=model.predict([book_arr,user])
pred

313/313 [==============================] - 1s 2ms/step


array([[3.6240232],
       [3.9056387],
       [2.2723782],
       ...,
       [3.6137924],
       [3.440524 ],
       [3.7283213]], dtype=float32)

In [38]:
pred=pred.reshape(-1)
pred

array([3.6240232, 3.9056387, 2.2723782, ..., 3.6137924, 3.440524 ,
       3.7283213], dtype=float32)

In [39]:
pred_ids=(-pred).argsort()[0:5]
pred_ids

array([7946, 3627, 9841, 5206, 6088])

In [40]:
books.iloc[pred_ids]

id   book_id  best_book_id   work_id  books_count        isbn  \
7946  7947   5031805       5031805  40769318           96  1433502410   
3627  3628     24812         24812     25599           14   740748475   
9841  9842  24019187      24019187  43618137           12  1250058902   
5206  5207     24818         24818    946589           28   836217357   
6088  6089    545425        545425    532703           88  9953320993   

            isbn13                                     authors  \
7946  9.781434e+12  Anonymous, Lane T. Dennis, Wayne A. Grudem   
3627  9.780741e+12                              Bill Watterson   
9841  9.781250e+12                             Brandon Stanton   
5206  9.780836e+12                              Bill Watterson   
6088           NaN              Safiy al-Rahman al-Mubarakfuri   

      original_publication_year  \
7946                     2002.0   
3627                     2005.0   
9841                     2015.0   
5206                     1993.0   
6088                     1979.0   

                                         original_title  ... ratings_count  \
7946                                                NaN  ...          8953   
3627                     The Complete Calvin and Hobbes  ...         28900   
9841                        Humans of New York: Stories  ...         12527   
5206  The Days Are Just Packed: A Calvin and Hobbes ...  ...         19143   
6088   الرحيق المختوم: بحث في السيرة النبوية على صاح...  ...         10558   

     work_ratings_count  work_text_reviews_count  ratings_1  ratings_2  \
7946              10784                      262         98         90   
3627              29968                      861        120        154   
9841              12852                     1210        191        211   
5206              20374                      228        114        149   
6088              13177                     1141        145        205   

      ratings_3  ratings_4  ratings_5  \
7946        367       1152       9077   
3627        693       3117      25884   
9841        901       3231       8318   
5206        942       3636      15533   
6088        919       2664       9244   

                                              image_url  \
7946  https://images.gr-assets.com/books/1410151002m...   
3627  https://images.gr-assets.com/books/1473064526m...   
9841  https://images.gr-assets.com/books/1430176879m...   
5206  https://images.gr-assets.com/books/1418211162m...   
6088  https://images.gr-assets.com/books/1289025514m...   

                                        small_image_url  
7946  https://images.gr-assets.com/books/1410151002s...  
3627  https://images.gr-assets.com/books/1473064526s...  
9841  https://images.gr-assets.com/books/1430176879s...  
5206  https://images.gr-assets.com/books/1418211162s...  
6088  https://images.gr-assets.com/books/1289025514s...  

[5 rows x 23 columns]